# base image based on alpine (this is very insecure)
FROM python:3.7-alpine

# set working directory
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

# add and install requirements
COPY ./Pipfile /usr/src/app/Pipfile
COPY ./Pipfile.lock /usr/src/app/Pipfile.lock
RUN pip install pipenv
RUN pipenv install --deploy --system

# add app
COPY . /usr/src/app

# run server
CMD python manage.py run -h 0.0.0.0